import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import api from '../api/api';

export default function Login() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const navigate = useNavigate();
  const finish = data => { localStorage.setItem('talentlens_token', data.token); localStorage.setItem('talentlens_user', JSON.stringify(data.user)); navigate('/'); };
  useEffect(() => { const clientId = import.meta.env.VITE_GOOGLE_CLIENT_ID; if (!clientId) return; const script = document.createElement('script'); script.src = 'https://accounts.google.com/gsi/client'; script.async = true; script.onload = () => window.google.accounts.id.initialize({ client_id: clientId, callback: async response => { try { finish((await api.post('/auth/google', { credential: response.credential })).data); } catch (err) { setError(err.response?.data?.message || 'Google sign-in failed.'); } } }); document.head.appendChild(script); return () => script.remove(); }, []);
  const submit = async event => { event.preventDefault(); setError(''); setLoading(true); try { finish((await api.post('/auth/login', { email, password })).data); } catch (err) { setError(err.response?.data?.message || 'We could not sign you in.'); } finally { setLoading(false); } };
  const google = () => { if (!import.meta.env.VITE_GOOGLE_CLIENT_ID || !window.google) return setError('Add VITE_GOOGLE_CLIENT_ID and GOOGLE_CLIENT_ID to enable Google sign-in.'); window.google.accounts.id.prompt(); };
  return <div className="auth-page"><section className="auth-showcase"><Link to="/login" className="auth-brand"><span className="spark">✦</span>TalentLens</Link><div className="showcase-copy"><span className="mini-label">Smarter hiring starts here</span><h1>Make every<br /><em>resume count.</em></h1><p>Turn a growing pile of applications into a clear, confident shortlist.</p></div><div className="orbit"><span>✦</span><span>✦</span><span>✦</span></div><div className="quote-card"><div className="quote-avatar">R</div><p>“TalentLens gave our team the focus to hire with confidence.”</p><small>Riya Patel · People Operations</small></div></section><section className="auth-panel"><div className="auth-card"><div className="auth-heading"><span className="welcome-dot"></span><span>WELCOME BACK</span><h2>Sign in to TalentLens</h2><p>Enter your details to continue screening.</p></div>{error && <div className="error-alert">{error}</div>}<button className="google-button" type="button" onClick={google}><span className="google-g">G</span> Continue with Google</button><div className="divider"><span></span>or continue with email<span></span></div><form onSubmit={submit}><label>Email address<input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@company.com" required /></label><label>Password<div className="password-wrap"><input type={showPassword ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter your password" required /><button type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? 'Hide' : 'Show'}</button></div></label><div className="auth-row"><label className="remember"><input type="checkbox" /> Remember me</label><a href="#reset" onClick={e => { e.preventDefault(); setError('Ask your workspace administrator to reset your password.'); }}>Forgot password?</a></div><button className="auth-submit" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}</button></form><p className="auth-footer">New to TalentLens? <Link to="/register">Create an account</Link></p></div></section></div>;
}
