import { useEffect, useRef, useState } from 'react';
import api from '../api/api';
import CandidateCard from '../components/CandidateCard';

export default function UploadPage() {
  const [files, setFiles] = useState([]), [candidates, setCandidates] = useState([]), [loading, setLoading] = useState(false), [message, setMessage] = useState(''); const input = useRef();
  const refresh = async () => { try { setCandidates((await api.get('/candidates')).data); } catch (e) { setMessage(e.response?.data?.message || 'Could not load candidates.'); } }; useEffect(() => { refresh(); }, []);
  const addFiles = files => setFiles(Array.from(files).filter(f => /\.(pdf|docx|txt)$/i.test(f.name)));
  const parse = async () => { if (!files.length) return setMessage('Choose at least one PDF, DOCX, or TXT resume.'); setLoading(true); setMessage(''); const form = new FormData(); files.forEach(file => form.append('resumes', file)); try { const { data } = await api.post('/upload/parse', form); const failed = data.results.filter(result => result.status === 'failed'); const failureDetails = failed.map(result => `${result.original_filename}: ${result.error}`).join(' '); setMessage(failed.length ? `${data.results.length - failed.length} parsed; ${failed.length} could not be parsed. ${failureDetails}` : `Successfully parsed and saved ${data.results.length} candidate profile(s).`); if (!failed.length) setFiles([]); await refresh(); } catch (e) { setMessage(e.response?.data?.message || 'Upload failed. Check that the API server is running.'); } finally { setLoading(false); } };
  return <div className="workspace-page"><div className="workspace-heading"><div><h1>Resume Parser &amp; Database</h1><p>Upload candidate resumes in PDF, DOCX, or TXT format. Extract skills and a clear candidate summary automatically.</p></div></div>{message && <div className="notice">{message}</div>}<section className="upload-shell"><div className="resume-drop" onClick={() => input.current.click()} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); addFiles(e.dataTransfer.files); }}><span className="upload-cloud">⇧</span><strong>Click to select or drag and drop resumes</strong><small>Supports multi-file upload (.PDF, .DOCX and .TXT format)</small><input ref={input} type="file" accept=".pdf,.docx,.txt" multiple onChange={e => addFiles(e.target.files)} /></div>{files.length > 0 && <div className="selected-files">{files.map(file => <span key={file.name}>{file.name}</span>)}<button onClick={parse} disabled={loading}>{loading ? 'Parsing resumes…' : `Parse ${files.length} resume${files.length > 1 ? 's' : ''}`}</button></div>}</section><div className="section-title"><h2>Stored Candidates <b>{candidates.length}</b></h2><button onClick={refresh}>↻ Refresh</button></div><div className="candidates-grid">{candidates.map(candidate => <CandidateCard candidate={candidate} key={candidate.id} onDelete={id => setCandidates(candidates.filter(c => c.id !== id))} />)}</div>{!candidates.length && <div className="empty-state"><p>No resumes stored yet. Upload a resume to build your screening candidate pool.</p></div>}</div>;
}
